### ISSUE TITLE
Ember 2.0

### ISSUE THREAD

**Issue by lukesargeant** [EmberSherpa/ember-helpers-render-component#1]
Sorry if this is the wrong place to discuss this, but I'm interested in using this helper to create a dashboard with user configurable widgets. My only concern is that because it's a new project I am keen to migrate to Ember 2.0 as soon as possible.

Does this helper still have a place in Ember 2.0? Is it compatible with the React philosophies that Ember seems to be adopting?

Since this feels a bit like breaking the ember happy use case (route > controller > Template > components) it would be great to have a few examples and a bit more information on the repo Readme.md to give confidence in not just this helper but the approach in general.

Appreciate your time.

**Comment by taras** [comment]
> Does this helper still have a place in Ember 2.0?

Yes, in fact it was added to Ember. I'm not sure what it's status is yet, but it in master (and probably Canary) https://github.com/emberjs/ember.js/pull/10093

> Is it compatible with the React philosophies that Ember seems to be adopting?

Yes, it will follow the same conventions as all components in Ember 2.0.

> Since this feels a bit like breaking the ember happy use case (route > controller > Template > components) it would be great to have a few examples and a bit more information on the repo Readme.md to give confidence in not just this helper but the approach in general.

In Ember 2.0, Controllers + Views will be replaced with Routable Components. Checkout this video for more information http://bit.ly/1EUAxvb
